### ISSUE TITLE
Select which sheet to read

### ISSUE THREAD

**Issue by makostadima** [tercen/readxl_operator#1]
I just had a one-to-one session with Ana from iTeos and her image analysis reports the results in excel spreadsheets with multiple sheets.

It would be nice to have the option to select every time which sheet to upload, without her having to save the sheet she's interested in in a seprate excel file.

**Comment by agouy** [comment]
@makostadima From [Release 1.2.1](https://github.com/tercen/readxl_operator/releases/tag/1.2.1) we are able to specify the sheet position / index as a setting. It throws an error if the sheet is not existing.
