### ISSUE TITLE
Reading excel spreadhseets online (e.g. from Google Drive)

### ISSUE THREAD

**Issue by makostadima** [tercen/readxl_operator#2]
I just had a use case (personal not of a client) that I'd like to read into Tercen some data from an excel spreadsheet from my Tercen Google Drive.

I had to export the file and then upload it onto Tercen.

It'd be great if the operator instead could read directly from the Google Drive by providing the URL link.

**Comment by agouy** [comment]
I don't think it would be possible with an operator unfortunately. We would need to be able to interactively check google credentials to read from google drive, even if the spreadsheet is publicly available.
