### ISSUE TITLE
tercen.Stage will not import file. - memory issue.

### ISSUE THREAD

**Issue by martin1english** [tercen/readxl_operator#3]
![image](https://github.com/user-attachments/assets/bb33b844-a013-45c8-85d3-af548a40b194)

[50000 EXCEL Records.xlsx](https://github.com/user-attachments/files/16613664/50000.EXCEL.Records.xlsx)

Not sure if this is a server or operator issue.

**Comment by agouy** [comment]
Happens on tercen.com as well. Investigating further.

**Comment by agouy** [comment]
Readxl requires a higher base memory than other operators. This is fixed now.
